### ISSUE TITLE
create separate plugin ESPHome

### ISSUE THREAD

**Issue by tprelog** [tprelog/iocage-homeassistant#10]
@CyanoFresh

I have several reasons that I include AppDaemon and the Configurator with the Home Assistant Core FreeNAS plugin.

I am going to create a separate FreeNAS plugin for ESPHome unless you have a reason it should be included here.

We can still add ESPHome in Home Assistant using the panel_iframe. Is this enough or does ESPHome need to be physically installed in the same iocage-jail as Home Assistant?

**Comment by CyanoFresh** [comment]
In my setup I use secrets.yml from home assistant folder.
Not sure if the same jail is requirement, haven't tried.

**Comment by tprelog** [comment]
So right now, if you need ESPHome to share any files from the home assistant folder, the easiest method is to install ESPHome in this same jail. This is exactly why I include AppDaemon and Configurator.

The only reason to install ESPHome in the same jail as Home Assistant, is to locate the secrets file in the Home Assistant directory but this is not required and it is only one file. I do not think this is enough reason to include ESPHome in the Home Assistant plugin.

I think it will be better for ESPHome if it is a separate FreeNAS plugin. There is still the ability to create and manage a separate secrets.yml inside the esphome jail. If you really must share the same jail, the option will remain but it become an "advanced option" that requires the command.

I can't even keep up with everything I want to do one thing is to update the FreeNAS guide to include how to create a single, separate dataset to hold the configuration folders. This configuration dataset,(I think as long as the permissions match) can be added as shared storage between multiple plugins (or jails).

I'll call it the HassBSD FreeNAS plugin collection and anything in that collection will include a helper script that accepts some global setting that is the same in every plugin. You will just set that the same in every HassBSD plugin and it will help provide any easy way to make sure everything matches correctly. You would do this in each jail that shares the config dataset.

This will be the best of both worlds as plugins would remain separate but you would still be able to have esphome in one jail, store it's secrets in the homeassistant folder of another jail.  In addition, with keeping configuration outside the jail dataset on its own we can use zfs snapshots for additional backup. I mean we already practically have built in version control on a filesystem level built right in. 

The whole thing will be like be like some kind mutant love child, that resulted from that crazy night Hassbian and Hass.io got drunk and had a three-way with FreeNAS :rofl: 

So anyways ESPHome is moving to its own plugin. If you already have it installed, it will continue to function as it is but futures installs of the Home Assistant plugin will not include ESPHome by default.

**Unless ESPHome absolutely stops working and the only solution is to install it in this jail** (seems very unlikely) the [ESPHome FreeNAS plugin will be separate](https://github.com/tprelog/iocage-esphome).

I'm sorry this will be a breaking change for your configuration but would you give this a try and let me know if it is terrible or not to make this adjustment? I have not used ESPHome yet but at least as far as compiling and downloading firmware, everything seems exactly the same.

```
iocage fetch -P esphome -g https://github.com/tprelog/freenas-plugin-index.git
```

**If you get error -- plugin not found,** you need to either manually `git pull` the updates. Or you can just delete my plugin repository from you FreeNAS then try the command again. This will force it to download updated plugins.

The plugin repos are stored inside you `iocage` dataset.

To pull updated plugin manifest you can
```
git -C YOUR_PATH_TO/iocage/.plugins/github_com_tprelog_freenas-plugin-index_git pull
```
If that doesn't work or you just want delete and force a complete new download
```
rm -rf  YOUR_PATH_TO/iocage/.plugins/github_com_tprelog_freenas-plugin-index_git
```

**Comment by tprelog** [comment]
I've updated the console to no longer include ESPHome by default.

The esphome menu can be manually re-enabled using.
```
sysrc esphome_menu=1
```

the restarting the `hassbsd` script

**Comment by tprelog** [comment]
Closing this -- There is now a separate FreeNAS Community plugin for ESPHome
