### ISSUE TITLE
devfs rules delete when stopping jail

### ISSUE THREAD

**Issue by basnagel** [tprelog/iocage-homeassistant#11]
When I restarted the home assistant plugin my Conbee2 stick (cuaU0) stopped showing up in the jail.
After a lot of searching I found a iocage issue describing iocage deleting deleting devfs ruleset on stopping the jail.

Not a bug you can fix(I read it is fixed), but maybe good to mention in your guide.
https://github.com/iocage/iocage/issues/1138

**Comment by tprelog** [comment]
Thanks for reporting this. I have noticed this issue myself sometimes but was not aware of the reported bug in iocage. I will add some notes about this about this, as well as some basic trouble shooting for the devfs-ruleset.

The point of this plugin is trying to avoid the command line as much as possible but sometimes it is still necessary. For example restarting the jail from the command line will show which ruleset is being used (and here we can clearly see it is correct on shut down but not when the jail is restarted)
```
troy@freenas~ $ sudo iocage restart homeassistant
* Stopping homeassistant
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 99 OK
  + Removing jail process OK
  + Executing poststop OK
* Ruleset 99 does not exist, using defaults
No default gateway found for ipv6.
* Starting homeassistant
  + Started OK
  + Using devfs_ruleset: 10
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
  + DHCP Address: 10.10.1.18/24
```

The easiest workaround seems to be executing the `zwave-ruleset.sh` script, 
```
troy@freenas~ $ sudo ./zwave-ruleset.sh
```

Now (re)starting the jail will use the correct devfs-ruleset
```
troy@freenas~ $ sudo iocage restart homeassistant
* Stopping homeassistant
  + Executing prestop OK
  + Stopping services OK
  + Tearing down VNET OK
  + Removing devfs_ruleset: 10 OK
  + Removing jail process OK
  + Executing poststop OK
No default gateway found for ipv6.
* Starting homeassistant
  + Started OK
  + Using devfs_ruleset: 99
  + Configuring VNET OK
  + Using IP options: vnet
  + Starting services OK
  + Executing poststart OK
  + DHCP Address: 10.10.1.18/24
```

If you need to restart the entire homeassistant jail, you can also work around this by using a `-s` "soft restart". But again this requires using the command line to restart the jail
```
troy@freenas~ $ sudo iocage restart -s homeassistant
Soft restarting homeassistant (homeassistant)
```

**Comment by tprelog** [comment]
Seems this is either fixed or just won't be an issue TrueNAS Core 12 -- The 12.1-RELEASE of this plugin will have the `devfs_ruleset` included in the plugin manifest. I can not say for sure if the `devfs_ruleset` is still being deleted or not but either way in my testing so far, the`devfs_ruleset` is being correctly created and applied on every startup and jail restart in TrueNAS Core 12

**Comment by tprelog** [comment]
This plugin is not longer supported on **FreeNAS**

On TrueNAS Core, this plugin will automagically create the devfs_ruleset from the plugin manifest
