### ISSUE TITLE
Update Home Assistant

### ISSUE THREAD

**Issue by soloam** [tprelog/iocage-homeassistant#12]
Hello I tried to update Home Assistant to the new version, but I can't. I tried with the freenas gui, but in the end I'm still in 0.104.3. I tried to go to the venv and update via "python3 -m pip install --upgrade homeassistant" I tried "source /srv/homeassistant/bin/activate" but I get "Badly placed ()'s."

Can you help me?

thank you

**Comment by tprelog** [comment]
Couple things.

Can you say what FreeNAS you are on and when / how you installed HA? 
This will help me determine what options are available for you moving forward

>  I tried with the freenas gui,

Even with the new FreeNAS 11.3 plugin - The upgrade plugin button the FreeNAS gui will never upgrade Home Assistant - This is briefly explained in the following link for the menu

If you are using the new plugin on FreeNAS 11.3 will find a simple menu is available when you log into the jail. You can upgrade homeassistant from it's service menu. 
There is [an example of using the menu here](https://community.home-assistant.io/t/home-assistant-core-freenas-community-plugin/170542/17?u=troy)

---

**In any case, this should always work**
```
pip3 install --upgrade homeassistant
```

> I tried "source /srv/homeassistant/bin/activate" but I get "Badly placed ()'s."

Your trying to do this as root -- You need to be hass

> I tried to go to the venv and update via "python3 -m pip install --upgrade homeassistant"

That's not the correct command


### Manual upgrade homeassistant
Assuming you are _starting from your FreeNAS console_
```
iocage console YOUR_JAIL
```

_Inside the jail_
```
service homeassistant stop

su - hass
source /srv/homeassistant/bin/activate
pip3 install --upgrade homeassistant
deactivate && exit

service homeassistant start
```

---

Also be sure to go through the release notes for Home Assistant, Especially breaking changes - You may likely need to edit your config in some ways, especially starting with 0.107.

**Comment by soloam** [comment]
I found the problem, I was not doing the su -u hass I was running with the jail root! That solved the problem!

Thank you and sorry for the confusion
