### ISSUE TITLE
Supervisor

### ISSUE THREAD

**Issue by dkalinai** [tprelog/iocage-homeassistant#13]
Are there any plans to make it install supervisor as well? Kind of missing that part...

**Comment by tprelog** [comment]
Sorry no. It is not even possible. The underlying technology is just not available on FreeNAS

The only way to run the Supervised install on FreeNAS is to us a VM running Linux

It is my option, the easiest guide for running Supervised on FreeNAS can be found [HERE](https://community.home-assistant.io/t/alternative-way-of-running-hassio-on-freenas-without-iocage-or-docker/133738?u=troy)

**Comment by dkalinai** [comment]
Oh well was worth asking, i already got a vm with hassio, was just thinking if there was a way to make it more tidy :) thanks for your time
