### ISSUE TITLE
PyNaCl error on fresh plugin install

### ISSUE THREAD

**Issue by wdreinhart** [tprelog/iocage-homeassistant#36]
Hello,
I'm having some trouble installing on TrueNAS-12.0-U2 (upgraded today from 11.3-U5).  I followed the "No More HASS" and "Plugin Upgrade From FreeNAS to TrueNAS Core" steps in the wiki - backed up my old configuration in /home/hass, deleted the old plugin, and installed a fresh instance from the TrueNAS web ui, added a mountpoint for my configuration, started the plugin, and it offered me the onboarding screen instead of my Lovelace dashboards.  I tried to use the console menu to check that it was seeing my configuration correctly, and got a long PyNaCl build error.  It seems to be looking for cpp in /lib instead of /usr/bin for some reason.  Complete output attached.
[hass_pynacl_err.log](https://github.com/tprelog/iocage-homeassistant/files/5976635/hass_pynacl_err.log)

**Comment by tprelog** [comment]
:thinking: This could be a few things

For the errors you are seeing - looks like it doesn't like the default path I have set in the last commit - interestingly PyNaCl 1.4.0 installs just fine, but it's not the correct version for Home Assistant - I'll get that changed back.

For now, please reset the path, delete the existing `.cache` directory and try installing `PyNaCl` again
```bash
iocage console $JAIL_NAME
# Press `0` to exit the menu

sysrc homeassistant_path="/sbin:/bin:/usr/sbin:/usr/bin"
rm -r /home/homeassistant/.cache
service homeassistant install PyNaCl==1.3.0
```

If this is successful, you can try running the check_config again
```bash
service homeassistant check_config
```

---

When you add your mount point, if there was existing configuration, you should just log back in like nothing happened... When you say you've reached onboarding, it indicates the directory may have been copied wrong or not mounted correctly.

Please check if the configuration is in the following location (also have a peek at the `configuration.yaml` you find, just to be sure it's _your_ configuration)

```bash
iocage console $JAIL_NAME
# Press `0` to exit the menu

ls -l /home/homeassistant/homeassistant
```

(yes it should be `homeassistant/homeassistant` - that's `homeassistant` twice - once for the user and once for the service... it's my least favorite part of this plugin and why I held onto `hass` for so long)

Anyways please try the two suggestions mentioned and report back

**Comment by wdreinhart** [comment]
Thanks, that fixed the PyNaCl error.  
Unfortunately it looks like my backup was bad, it's mounted correctly but it looks like the default configuration.yaml inside and outside the jail.
