### ISSUE TITLE
HomeAssistant Core cannot restart itself

### ISSUE THREAD

**Issue by davidlang42** [tprelog/iocage-homeassistant#40]
Since updating to the latest version of the TrueNAS plugin, restarting HA from within the HA web ui no longer works. It previously worked (for a long period of time) running the old version.

The web UI I am talking about is under Configuration > Server Controls > Server Management > Restart
![image](https://user-images.githubusercontent.com/37281992/116526127-9c379980-a91c-11eb-8f42-448446d91267.png)

When the restart button is pressed, HA core stops, but does not restart.
Opening a shell in the jail and running `service homeassistant status` shows that it has stopped, but no amount of waiting makes it come back online. I have to manually run `service homeassistant start` or `service homeassistant restart`. Then HA core works again.

Using the shell "HomeAssistant menu" option for 'restart' does work, but for obvious reasons thats not a great workaround when there is a button in HomeAssistant itself specifically to restart it.

Happy to help diagnose the problem, but not sure where to start or what could have changed. First thought- permissions of some sort, but who knows.

**Comment by tprelog** [comment]
>When the restart button is pressed, HA core stops, but does not restart.

There's been a few other people with this issue over the last few years, but I've never been able to reproduce this myself
- good news...  It _should_ still work
- bad news... It's harder for me to find the issue

>latest version of the TrueNAS plugin

Please run `iocage list -l` from the TueNAS console and share what (FreeBSD) RELEASE  it is running.

I assume you ran a Plugin UPDATE from the TrueNAS UI... Is this correct ?

Did Home-Assistant reinstall itself during the update ?

**Comment by davidlang42** [comment]
Kind of good to know its an existing issue even if its not reproducible!
The plugin jail is running `12.1-RELEASE-p13`

Yes, I did plugin update from the TrueNAS UI. I didn't do anything manual to HA after the update, it just still worked as it did before, so I assume that means yes it did reinstall itself?

If there are any log files I can look into/send you, or things you can think of for me to try, let me know.

**Comment by tprelog** [comment]
> The plugin jail is running `12.1-RELEASE-p13`

Ah, we might be in luck here. You jail should be on `12.2-RELEASE-pX` (I'm not sure the exact patch level off hand)

Try running the **Jails** UPDATE -- Home Assistant _should_ reinstall itself during the update. If not, we may need to do so manually. Keep in mind, after a reinstall, when Home Assistant starts for the first time, it can take a considerable amount of time before the UI become reachable again. The amount of time will vary, depending on number of integrations you have and the specs of your server. I have quad core xeon and it took about 10 min ... one user reported needing to wait around 35 minutes.

If you have enabled logging in your Home Assistant configuration, you can check the progress by following the logfile

- https://www.home-assistant.io/integrations/logger/

```yaml
logger:
  default: info
```

To follow the logs, use the following

```bash
iocage console $JAIL_NAME
# Press 0 to exit menu
service homeassistant logs -f
```

**Comment by davidlang42** [comment]
I selected the jail and chose update, it showed the in progress dialog for a few minutes then said it failed with the error "no updates found for jail" (not exact wording). Is there something special I need to do to make the jail go to the next release? Or can I run `pkg upgrade` in the jail to do the same thing?

**Comment by tprelog** [comment]
I don't think `pkg update` is enough to update the jail's RELEASE. (That's what we're after here)

Please try following the steps in this post
- https://community.home-assistant.io/t/home-assistant-core-truenas-core-community-plugin/170542/392?u=troy

**Comment by davidlang42** [comment]
Followed instructions in your post and it did the jail upgrade as suggested, now at 12.2-RELEASE-p6 according to GUI.
Restart server (from within HA) now working! Thanks :)
