### ISSUE TITLE
Upgrade to Home Assistant 2021.10 - Failed to build cryptography

### ISSUE THREAD

**Issue by tprelog** [tprelog/iocage-homeassistant#44]
Reported [HERE](https://community.home-assistant.io/t/home-assistant-core-truenas-core-community-plugin/170542/482?u=troy)

Building the wheel for cryptography requires Rust >=1.41.0.

```
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/share/homeassistant/bin/python3.8 /usr/local/share/homeassistant/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp7t48ovwx
       cwd: /tmp/pip-install-7sttgmrm/cryptography
[...]
This package requires Rust >=1.41.0.
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
```

**Comment by adorobis** [comment]
> Solution is to install `rust` in the jail.

Confirmed from my side, upgrade works ok after installing rust in the jail. Many thanks for quick response!

**Comment by cascer1** [comment]
Installing rust doesn't fix the issue for me.

> ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

**Comment by cascer1** [comment]
Hi tprelog, 

please see the output below. I'm not sure why it's using plugin verison 20210307. I've tried upgrading several times but this never worked. During my upgrade attempts, I get a lot of warnings like `pkg: Lua script failed`.

```
root@homeassistant:~ # sysrc -a | grep plugin
plugin_initialized: 5.0.20201229
plugin_version: v6-20210307
```

See [this gist](https://gist.github.com/cascer1/9ee6680f5eaae5fda47541ec407e8b89) for the output of the second command.

**Comment by tprelog** [comment]
> Please let me know if you would like me to keep the old jail around so I can help you figure out what's going on.

Yes, debugging will be helpful if we can figure out why the Plugin Update has failed.

From the old jail, please share output from the following commands.

```
iocage console $JAIL_NAME
# press 0 to exit menu
echo $path
ls -l .plugin/bin
cat .login
cat /etc/pip.conf
sysrc -a | grep homeassistant
python3.8 --version
service homeassistant test
```

And ensure the following directories have been removed
```
rm -rf /root/bin
rm -rf /home/homeassistant/.cache
```

**Comment by mvanbaak** [comment]
You could also set an environment variable to install `cryptography` without needing `rust`

```bash
setenv CRYPTOGRAPHY_DONT_BUILD_RUST 1
python3 -m pip install homeassistant
```

**Comment by tprelog** [comment]
This should be resolved for some some time now.
