### ISSUE TITLE
ESPHome support

### ISSUE THREAD

**Issue by CyanoFresh** [tprelog/iocage-homeassistant#5]
Hi
I also need ESPHome with home assistant. Do you have any plans to implement this? Setup is similar to configurator.
Thanks for you work!

**Comment by tprelog** [comment]
Hello
I had a quick look at ESPHome and it looks like I can I add this pretty easily. I'll have a closer look and see what I can do this weekend

**Comment by CyanoFresh** [comment]
yeah, there are problems with usb uploading on hassio addon too. 

I think `mdi:chip` is good

**Comment by tprelog** [comment]
I should have this done today.

Are you using [the new 11.3-RELEASE plugin](https://github.com/tprelog/iocage-homeassistant/tree/11.3-RELEASE)?

**Comment by CyanoFresh** [comment]
> I should have this done today.
> 
> Are you using [the new 11.3-RELEASE plugin](https://github.com/tprelog/iocage-homeassistant/tree/11.3-RELEASE)?

i am on 11.2 but can install 11.3 if needed

**Comment by tprelog** [comment]
I've added this as an option for the 11.3-RELEASE.  I can't say it worth all the trouble of upgrading FreeNAS before your actually ready, just to have this.

I think you could still add this to your existing install but we'll have to do it manually. I think it would be pretty easy - Let me know if you rather just add this to your existing install and I'll put some steps down to writing.

A clean install of the 11.3 plugin will just have a menu option to install ESPHome
(Sorry fancy menu comes in the 11.3-Release)

![image](https://user-images.githubusercontent.com/35702532/72175367-03d57880-33aa-11ea-97f5-4abce51d8814.png)

**Comment by tprelog** [comment]
Ok so I think this really only a few steps. I don't an 11.2-RELEASE running to test this so we'll start by taking a snapshot of your existing jail before we make any changes.

This is assuming you jail name is `homeassistant`

Begin from you FreeNAS console
```
iocage snapshot -n no_esphome homeassistant
```

I really don't see any reason the updated `post_install` won't still work in the 11.2-RELEASE so we going to download a few a files and give this a shot. If anything goes wrong we can undo the changes by rolling back the snapshot
```
iocage console homeassistant
pkg install -y gcc wget

wget -O /usr/local/ect/rc.d/esphome https://raw.githubusercontent.com/tprelog/iocage-homeassistant/11.3-RELEASE/overlay/usr/local/etc/rc.d/esphome
chmod +x /usr/local/ect/rc.d/esphome

wget -O /root/post_install.sh https://raw.githubusercontent.com/tprelog/iocage-homeassistant/11.3-RELEASE/post_install.sh
chmod +x /root/post_install.sh

/root/post_install.sh esphome
```

I think that should be it to have ESPHome installed and running.

You'll still need to add the iframe to your Home Assistant configuration

**Comment by CyanoFresh** [comment]
wow it works. Even better than my manual setup (I had errors with platformio on freebsd). Thanks :)

**Comment by flufftronix** [comment]
I haven't used ESPHome at all, but am running an iohyve instance of RancherOS to make running a few services easier on me (Almond, Caddy, MotionEye).. since these run on Linux I bet ESPHome would work fine there. Not an all-in-one solution or anything, but if you're just looking to get up and running that might be worth looking to.

**Comment by CyanoFresh** [comment]
Found a solution for esp32 (see updated comment). Now everything is working fine. 
@tprelog are you going to add esphome to README?

**Comment by tprelog** [comment]
@CyanoFresh 
 Awesome thanks! I'll update the plugin to include your solution for the esp32, then I'll add ESPHome to the README.

I'll try to do this after work today

**Comment by tprelog** [comment]
@CyanoFresh

It's done my friend. But [only in the 11.3-RELEASE](https://github.com/tprelog/iocage-homeassistant/tree/11.3-RELEASE)

I have a few more things to do but I'm going to make 11.3 the default branch very soon.

**Comment by CyanoFresh** [comment]
Nice, thank you very much
