### ISSUE TITLE
Feature request: Automatically take snapshot of HA jail before HA upgrade

### ISSUE THREAD

**Issue by adorobis** [tprelog/iocage-homeassistant#56]
I have already had a few times a case when something didn't work as expected after HA upgrade and I was saved by taking a snapshot just before the upgrade. How about taking the snapshot automatically before every upgrade? Just in case someone forgets to take it manually?
I'm taking it using the following command:
```
zfs snapshot -r [pool_name]/iocage/jails/[jail+_name]/root@manual-`date "+%Y-%m-%d_%H:%M"`
```

**Comment by tprelog** [comment]
Not exactly that straightforward but there's a few possibilities here, I'll try to quickly explain.

Normally, you can not take snapshots from _inside_ the jail, but this is were we run the Home Assistant update from. (When you run the Plugin UPDATE, TrueNAS already takes a snapshot at the beginning)

It could be possible to turn on some jail attributes and try to have the jail create and manage its own sub-dataset. I think we could install the venv inside that and could be managed (snapshots or rollback) from inside the jail. This would take the most experimentation, so is the least likely for me to implement


The easiest thing to do - might be create a little a help script that gets run from TrueNAS (not inside the jail)

```bash
#!/usr/bin/env bash

pool_name=tank
jail_name=home-assistant

zfs snapshot -r [pool_name]/iocage/jails/[jail_name]/root@manual-`date "+%Y-%m-%d_%H:%M"` \
  && iocage exec homeassistant service homeassistant upgrade homeassistant
```

The third option, and probably the easiest to get set-up inside Home Assistant, is to use the TrueNAS API - You'd still need to configure an API key so it's not something I can set-up to work out-of-the-box. I've used the [RESTful integration](https://www.home-assistant.io/integrations/rest/) to get [snapshots working from Home Assistant in the past](https://github.com/tprelog/iocage-homeassistant/wiki/daily-zfs-snapshots-from-Home-Assistant#expose-the-rest_command-as-a-service-using-this-packageyaml-file). The idea here, would  be basically create a script (or automation) that would trigger the snapshot and then run the update command, right from inside Home Assistant.

Or finally, we could just add some scripts to overlay folder-- To take snapshots from inside the jail, you'd need to use either ssh commands back to the host, or as mentioned, the RESTful api. I could probably setup a `curl `command to `POST` the API call for snapshot back to TrueNAS before running the update.


Thoughts on any particular approach?

**Comment by adorobis** [comment]
Thanks for quick reply and again comprehensive answer.
I have not realised that you can't take snapshots from within the jail, any other solution I think is smaller or larger workaround...
I think it is not worth it, anyway TrueNAS by default takes daily jail snaphots so basic security mechanism is in place (at least on my system). I would not go further than that.
