### ISSUE TITLE
Issues reinstalling plugin

### ISSUE THREAD

**Issue by tprelog** [tprelog/iocage-homeassistant#58]
Thank you @tprelog and yes please. 
I figured a reinstall would be on the cards but spent a bit of time trying to see if there was anything else I could do.

I tried updating Python and reinstalling Home Assistant with the lines above but It kept saying it didn't recognise the command 'homeassistant' after the failed plugin update.

I tried to restore from several different snapshots but it that didn't seem to do anything, after it was done it didn't roll back to 2021.3.4.

I tried following this [installation guide](https://community.home-assistant.io/t/home-assistant-core-truenas-core-community-plugin/170542) to reinstall but I kept coming up against errors.
`ERROR: Failed building wheel for cryptography`

I've tried a couple of times to install a new HA plugin but it's got stuck at 50% and said the jail was corrupt.
A search on this error came up with running
`iocage clean -a`
but I'm not 100% sure if this is safe to do

_Originally posted by @aliekiddo in https://github.com/tprelog/iocage-homeassistant/issues/52#issuecomment-1085499261_

**Comment by tprelog** [comment]
Moving our discussion to a new issue @aliekiddo since it's not directly related to startup issue caused by the OS checker

**Comment by aliekiddo** [comment]
Thanks @tprelog I was wondering if I should move this into another thread.

The good news is that after several attempts I've finally got another HA plugin installed.
This did have me wondering if I should move to TrueNAS Scale... literally just as the plugin finished installing.

I've had to do a re-build once before when moving from a VM on TrueNAS to the Core plugin as it would take hours to reboot.
I believe I copied over the configuration.yaml and automations.yaml to the new version and re-did a lot manually.

Is there a better way to get back up and running?

**Comment by tprelog** [comment]
> The good news is that after several attempts I've finally got another HA plugin installed.

Great to hear :+1: 

> This did have me wondering if I should move to TrueNAS Scale.

Depending on what you're running, it's definitely worth a look. My Home Assistant is pretty straight forward with minimal integrations so I never had any issues running in a jail. I ended up switching to Scale because of ESPHome. But I don't like running a whole Kubernetes stack for a single node home server and only a handful of apps.So I'm [using a hack](https://gist.github.com/tprelog/7988dc6b196775f33929beb19f0090d7) to enable and use native docker and docker-compose.

> I believe I copied over the configuration.yaml and automations.yaml to the new version and re-did a lot manually.

There's a wiki page to help move your config to an external dataset. It can be followed even if the jail is not running
- https://github.com/tprelog/iocage-homeassistant/wiki/external_dataset

As long as you copy the entire configuration directory (including all hidden files and folders) to a new install, Home Assistant will come back just as you left it in the previous install.

> Is there a better way to get back up and running?

Not specific to this plugin, but snapshots were usually my first line of defense for a quick recovery. But there is no automatic snapshot mechanism when updating Home Assistant from the console menu, it must be done manually. So my workflow for regular Home Assistant updates was:
1. ssh into my TrueNAS
2. [take manual snapshot of the jail](https://github.com/tprelog/iocage-homeassistant/wiki/Snapshots)
3. use `iocage console $jail_name` to gain access to jail
4. update Home Assistant using the [console menu](https://raw.githubusercontent.com/wiki/tprelog/iocage-homeassistant/img/v5_ha_console_menu.png)

Next best thing is moving your configuration to an external dataset. This way if the jail takes a crap, you just spin up a new jail and remount your config. First start-up after mounting your configuration will take extra time since Home Assistant still needs to reinstall all your integrations. Behind the scenes, this involves downloading and compiling additional python modules (building wheels). Some wheels like `cryptography` can take several minutes to build even with decent NAS hardware.

Typically my workflow for troubleshooting and/or reinstalling Home Assistant is as follows:
1. install new plugin (name it something like `$jail_name_test`)
2. wait for Home Assistant to install then go through onboarding, create a test user and reach the Home Assistant UI
2a. _do not_ install any integrations or add discovered devices at this time
3. confirm there are no errors in the log with this basic, default installation
3a. if my existing install has, or someone reports trouble with particular integration, I would try to configure that now

There are occasions something that is broke after an update to an existing installation will "just work" in a new install. If there are issues at step 3 I troubleshoot in this new jail. If I'm successful troubleshooting something here I will try to apply whatever fix I found back to the existing installation. Again there are occasions we've managed to fix something in a new install, but have been unsuccessful appling the fix back to an existing installation.

The remaining steps continue moving completely to a new installation

5. ssh into my TrueNAS
6. use `iocage console $jail_name_test` to gain access to the new jail
7. stop the homeassistant service
8. delete all content in the existing configuration directory (we need an empty directory to mount external dataset)
9. exit and stop the new jail
10. stop the existing jail
11. rename the existing jail `iocage rename $jail_name $jail_name_old`
12. rename the new jail `iocage rename $jail_name_test $jail_name`
13. add mount point for external dataset and start new jail
14. wait for Home Assistant to come up (my server has a Xeon E3-1245 v5 @ 3.50GHz and this took around 8-10 minutes)

**Comment by aliekiddo** [comment]
Thank you so much @tprelog for taking the time to help me out 😄 
I really have no idea what's wrong with my set up. It's not a beefy machine by any means - i5-3470T @ 2.90GHz + 12 GB RAM but it doesn't ever seem to be taxing itself - maybe it just wishes I'd spend more time with it... 

I've got everything back working, a restart of HA now takes seconds right now instead of a good 10-20 minutes.

This certainly makes the (probably someday) migration to Scale seem a little less scary as I wasn't exactly looking forward to re-doing HA.

Thankfully I've at least learned a few bits in the process of all of this 😄
